---
- name: Citus Health Integration Engine (CHIE) CCF Containers
  hosts: all
  vars_files:
    - ../conf/chie.secrets.conf.yml
    - ../conf/chie.common.conf.yml
  tasks:
    - name: Clone Citus Health Integration Engine (CHIE) CCF Containers
      git:
       name: https://{{ chp_github_account | urlencode }}:{{ chp_github_account_token | urlencode }}@github.com/CitusHealth/citus-health-integration-engine-appliance-ccf-containers.git 
       dest: '{{citus_health_containers_path}}'
      # Copy the CPR+ FHIR Facade Secret Conf file to CPR+ FHIR Facade CCF Container directory  
    - copy:
       src: ../conf/cpr.secrets.conf.json
       dest: '{{ wellsky_cpr_fhir_facade_secret_dest_file }}'
       owner: root
       group: root
       mode: 0644
    - name: Go to CPR+ FHIR Facade directory and install CPR+ FHIR Facade CCF container service
      command: chdir={{ wellsky_cpr_fhir_facade_path }} ccfmake start
    
    - name: Go to Nextgen Mirth Connect directory and install Nextgen Mirth Connect CCF container service
      command: chdir={{ nextgen_mirth_connect_path }} ccfmake start
